# Generated by Django 3.2 on 2021-05-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='advisorid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='userid',
            field=models.IntegerField(),
        ),
    ]
